trigger:
- main

variables:
  # --- Variables a configurar en la UI de la Pipeline ---
  # functionAppName: 'el-nombre-de-tu-function-app'
  # acrName: 'el-nombre-de-tu-acr'

  # --- Variables automáticas ---
  imageRepository: 'nombre-de-tu-imagen'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build and Push'
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      displayName: 'Build and Push Docker Image'
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(acrName) # Usa el nombre del ACR
        tags: |
          $(tag)

- stage: Deploy
  displayName: 'Deploy to Function App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    steps:
    - task: AzureFunctionAppContainer@1
      displayName: 'Deploy Function App on Container'
      inputs:
        azureSubscription: 'Conexión_a_tu_Suscripción' # Nombre de la Service Connection
        appName: $(functionAppName)
        imageName: '$(acrName).azurecr.io/$(imageRepository):$(tag)'